In [80]:
from pandas import Series, DataFrame
import pandas as pd, numpy as np, unittest
%matplotlib inline

In [2]:
obj = Series([5,3,2, -7, 2])
obj

0    5
1    3
2    2
3   -7
4    2
dtype: int64

In [3]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index

In [4]:
index

Index([u'a', u'b', u'c'], dtype='object')

In [5]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [6]:
test = ['a', 'b', 'c']
test

['a', 'b', 'c']

In [9]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [11]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio' : {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [12]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [15]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [16]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [17]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [18]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [19]:
obj.reindex(['a','b','c','d','e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [20]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [21]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [22]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                 columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [23]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [24]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [25]:
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill', columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [26]:
frame.ix[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [27]:
frame.drop('California', axis=1)

Ohio  Texas
a     0      1
c     3      4
d     6      7

In [29]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [30]:
obj['b']

1.0

In [31]:
obj[1]

1.0

In [32]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [34]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [35]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [36]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [37]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [38]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [41]:
data.ix[['Colorado', 'Utah'], [3, 2, 0]]

four  three  one
Colorado     7      6    4
Utah        11     10    8

In [44]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [45]:
data.ix[0]

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int64

In [47]:
data.ix[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [48]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [49]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=list('acde'))
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=list('acefg'))
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [50]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [51]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [52]:
s1.add(s2, fill_value=0)

a    5.2
c    1.1
d    3.4
e    0.0
f    4.0
g    3.1
dtype: float64

In [53]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [54]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [55]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [56]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.ix[0]

In [57]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [58]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [59]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [60]:
series2 = Series(range(3), index=list('bef'))
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [61]:
series3 = frame['d']

In [62]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [63]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [64]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [65]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.313984 -0.624762 -1.232465
Ohio   -1.434810 -0.942920  0.425848
Texas   0.307051  0.705791  1.119738
Oregon -1.364237 -0.463513 -1.157432

In [66]:
np.abs(frame)

b         d         e
Utah    0.313984  0.624762  1.232465
Ohio    1.434810  0.942920  0.425848
Texas   0.307051  0.705791  1.119738
Oregon  1.364237  0.463513  1.157432

In [67]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.748793
d    1.648711
e    2.352203
dtype: float64

In [68]:
frame.apply(f, axis=1)

Utah      1.546449
Ohio      1.860658
Texas     0.812687
Oregon    0.900723
dtype: float64

In [69]:
items = [1, 2, 3, 4, 5]
squared = [item ** 2 for item in items]
squared

[1, 4, 9, 16, 25]

In [86]:
def sum_of_squares(rng):
    return sum([i ** 2 for i in np.arange(1, rng + 1)])

In [87]:
class MyTest(unittest.TestCase):
    def test_sum_of_squares_100(self):
        self.assertEqual(sum_of_squares(100), 338350)

In [88]:
unittest.main()

AttributeError: 'module' object has no attribute '/Users/devan1989/Library/Jupyter/runtime/kernel-e5e226da-13f7-4a23-98ea-968865786fdd'

In [4]:
from pandas import DataFrame
import numpy as np
frameDev = DataFrame(np.random.rand(20).reshape((4,5)),
                    columns=list('12345'),
                    index=list('abcd'))
frameDev

1         2         3         4         5
a  0.458462  0.777072  0.875518  0.419192  0.464267
b  0.278714  0.693709  0.028926  0.193451  0.593409
c  0.086311  0.902976  0.369770  0.933029  0.664043
d  0.561941  0.452475  0.435640  0.400806  0.913101