In [3]:
from pandas import Series, DataFrame
import pandas as pd, numpy as np
%matplotlib inline

In [2]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [3]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [13]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=[1, 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
1      2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [7]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [8]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [14]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
1      2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [15]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
1      2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [16]:
val = Series([-1.3, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
1      2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.3
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [17]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
1      2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.3    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [18]:
del frame2['eastern']
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [21]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [22]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [23]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [24]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [25]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

### Index Objects

-> responsible for holding the axis labels and other metadata.

In [26]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index([u'a', u'b', u'c'], dtype='object')

In [27]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [28]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [29]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [30]:
'Ohio' in frame3.columns

True

In [31]:
2003 in frame3.index

False

### Essential Functionality
#### Reindexing

-> create a new object with the data conformed to a new index

In [32]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [33]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [34]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [37]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 5])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    purple
5    yellow
dtype: object

In [39]:
obj3.reindex(range(8), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    purple
5    yellow
6    yellow
7    yellow
dtype: object

In [43]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [44]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [45]:
states = ['Ohio', 'Texas', 'California', 'Utah']
frame.reindex(columns=states)

Ohio  Texas  California  Utah
a     0      1           2   NaN
c     3      4           5   NaN
d     6      7           8   NaN

In [47]:
frame.reindex(index=['a', 'b', 'c', 'd'], method='bfill',
              columns=states)

Ohio  Texas  California  Utah
a     0      1           2   NaN
b     3      4           5   NaN
c     3      4           5   NaN
d     6      7           8   NaN

In [48]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [49]:
frame.ix[['a', 'b', 'c', 'd'], states]

Ohio  Texas  California  Utah
a   0.0    1.0         2.0   NaN
b   NaN    NaN         NaN   NaN
c   3.0    4.0         5.0   NaN
d   6.0    7.0         8.0   NaN

#### Dropping entries from an axis

In [50]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [51]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [52]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [53]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

#### Indexing, selection and filtering

In [8]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [6]:
obj[1]

1.0

In [9]:
obj['b']

1.0

In [10]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

slicing with labels is different to normal python slicing, in that the endpoint is inclusive.

In [11]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [12]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [13]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [14]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [20]:
data[:1]

one  two  three  four
Ohio    0    1      2     3

In [21]:
data[data['three'] > 7]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [22]:
data > 5

one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [23]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [24]:
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [25]:
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [26]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [30]:
data.ix[:'Utah', 'one']

Ohio        0
Colorado    0
Utah        8
Name: one, dtype: int64

In [29]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [31]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

Indexing options with DataFrame:

obj[val]           - select single col or sequence of cols from the DF. Boolean/Slice

obj.ix[val]        - select rows

obj.ix[:, val]     - select cols

obj.ix[val1, val2] - select both rows/cols

reindex method     - conform one or more axes to new indexes

xs method          - select single row or col as a series by label

#### Arithmetic and Data Alignment 

In [33]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, 5.9, -1.4, 3.5], index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [34]:
s2

a   -2.1
c    3.6
e    5.9
f   -1.4
g    3.5
dtype: float64

In [35]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    7.4
f    NaN
g    NaN
dtype: float64

In [45]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [46]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [47]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [48]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

#### Operations between DataFrame and Series

In [49]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [50]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [51]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [52]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [53]:
series = frame.ix[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [56]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [57]:
series2 = Series(range(3), index=list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [58]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [59]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [60]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [61]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

#### Function Application and Mapping

In [62]:
#unfuncs with pandas objects
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.291683  1.371813  1.401723
Ohio    0.855863  0.338639 -0.189989
Texas  -0.275057  0.505658  0.429153
Oregon -0.375119 -0.969747  1.735034

In [63]:
np.abs(frame)

b         d         e
Utah    0.291683  1.371813  1.401723
Ohio    0.855863  0.338639  0.189989
Texas   0.275057  0.505658  0.429153
Oregon  0.375119  0.969747  1.735034

In [64]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.230982
d    2.341560
e    1.925023
dtype: float64

In [65]:
frame.apply(f, axis=1)

Utah      1.693406
Ohio      1.045852
Texas     0.780714
Oregon    2.704781
dtype: float64

In [66]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.375119 -0.969747 -0.189989
max  0.855863  1.371813  1.735034

In [70]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.29   1.37   1.40
Ohio     0.86   0.34  -0.19
Texas   -0.28   0.51   0.43
Oregon  -0.38  -0.97   1.74

In [71]:
frame['e'].map(format)

Utah       1.40
Ohio      -0.19
Texas      0.43
Oregon     1.74
Name: e, dtype: object

#### Sorting and Ranking

In [72]:
obj = Series(range(4), index=list('dabc'))
obj

d    0
a    1
b    2
c    3
dtype: int64

In [76]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [77]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=list('dabc'))
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [78]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [80]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [84]:
obj = Series([4, 7, np.nan, -3, 2])
obj

0    4.0
1    7.0
2    NaN
3   -3.0
4    2.0
dtype: float64

In [85]:
obj.sort_values()

3   -3.0
4    2.0
0    4.0
1    7.0
2    NaN
dtype: float64

In [88]:
#ranks
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [89]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [90]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64